# Generated by Django 5.0.6 on 2024-06-21 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_remove_bank_address_remove_bank_branch_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='announcement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='bank_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='banks.bank'),
        ),
    ]
