# Generated by Django 5.0.6 on 2024-06-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_branch_announcement_date_branch_manager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='bank_name',
            new_name='bank',
        ),
    ]
